CREATE TABLE IF NOT EXISTS Users(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Username VARCHAR(127) NOT NULL UNIQUE,
    Password VARCHAR(127) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Links (
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    PRIMARY KEY (ID)
);